/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_JavaRustFFI */

#ifndef _Included_test_JavaRustFFI
#define _Included_test_JavaRustFFI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_JavaRustFFI
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_JavaRustFFI_hello
  (JNIEnv *, jclass);

/*
 * Class:     test_JavaRustFFI
 * Method:    optimize_from_memory
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_test_JavaRustFFI_optimize_1from_1memory
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
